name: Actions

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Configurate
    run: |
      mkdir ${{github.workspace}}/_build && cd ${{github.workspace}}/_build
      cmake .. -DBUILD_TESTS=ON
      cmake --build .

  - name: my_exe
    run: ${{github.workspace}}/_build/my_exe

  - name: Run tests
    run: _build/my_test
    