name: Actions

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Configurate
    run: |
      mkdir ${{github.workspace}}/_build && cd ${{github.workspace}}/_build
      cmake ..
      cmake --build .

  - name: my_exe
    run: |
      ${{github.workspace}}/_build/main && echo -e "1\n2\n1"
  
    
  